language: node_js
sudo: true
node_js: stable
script:
- npm test
env:
  global:
  - CF_APP=tradeoff-analytics-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/tradeoff-analytics-nodejs
  skip_cleanup: true
notifications:
  email: false
